//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mntone.TwitterVideoUploader.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mntone.TwitterVideoUploader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Twitter Video Uploader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aspect ratio doesn’t fall within the range from 1:3 to 3:1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AspectRatioDoesNotFallWithinTheRange {
            get {
                return ResourceManager.GetString("AspectRatioDoesNotFallWithinTheRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio channel isn’t 1 or 2 ch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioChannelIsNot1Or2 {
            get {
                return ResourceManager.GetString("AudioChannelIsNot1Or2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio codec isn’t “AAC-LC” に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioCodecIsNotAacLc {
            get {
                return ResourceManager.GetString("AudioCodecIsNotAacLc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum duration of {0:0.00} sec exceeded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DurationExceeded {
            get {
                return ResourceManager.GetString("DurationExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File doesn’t exist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum filesize of {0:0.0} MB exceeded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilesizeExceeded {
            get {
                return ResourceManager.GetString("FilesizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum framerate of {0:0.00} fps exceeded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FramerateExceeded {
            get {
                return ResourceManager.GetString("FramerateExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mine type isn’t “video/mp4” に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MineTypeIsIncorrect {
            get {
                return ResourceManager.GetString("MineTypeIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (not authorized) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pixel aspect ratio isn’t square に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PixelAspectRatioIsNotSquare {
            get {
                return ResourceManager.GetString("PixelAspectRatioIsNotSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum resolution of {0}×{1} exceeded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResolutionExceeded {
            get {
                return ResourceManager.GetString("ResolutionExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum video bitrate of {0:0.0} Mbps exceeded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VideoBitrateExceeded {
            get {
                return ResourceManager.GetString("VideoBitrateExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video codec isn’t “H.264/AVC” に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VideoCodecIsNotH264Avc {
            get {
                return ResourceManager.GetString("VideoCodecIsNotH264Avc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video isn’t progressive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VideoIsNotProgressive {
            get {
                return ResourceManager.GetString("VideoIsNotProgressive", resourceCulture);
            }
        }
    }
}
